CREATE TABLE USERS
(
    EMAIL varchar(100),
    PASSWORD varchar(512) NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE GROUPS
(
    EMAIL varchar(100),
    GROUP_NAME varchar(100),
    PRIMARY KEY (EMAIL, GROUP_NAME)
);

CREATE TABLE TASKS
(
    TASK varchar(100),
    GROUP_NAME varchar(100),
    VALUE int(11) NOT NULL,
    DESCRIPTION varchar(255),
    PRIMARY KEY (TASK, GROUP_NAME)
);

CREATE TABLE TASKS_HISTORY
(
    TASK varchar(100),
    GROUP_NAME varchar(100),
    EMAIL varchar(100),
	DATE DATETIME
);

CREATE INDEX TASK_GROUP_IDX ON TASKS_HISTORY (GROUP_NAME); 
CREATE INDEX TASK_GROUP_EMAIL_IDX ON TASKS_HISTORY (GROUP_NAME, EMAIL); 